### ISSUE TITLE
User inscription

### ISSUE THREAD

**Issue by PhilippeRaymondHaikara** [TonyHaikara/silk-platform#12]
“Year of birth” should be a date picker

**Comment by pacman141** [comment]
C'est corrigé
![image](https://user-images.githubusercontent.com/17529387/121492247-012fe600-c9d7-11eb-8267-5f4802668ff5.png)

**Comment by ywarnier** [comment]
Confirmé. Ça a ensuite été changé pour un sélecteur d'année, ce qui est encore mieux.
