### ISSUE TITLE
Texts in english

### ISSUE THREAD

**Issue by PhilippeRaymondHaikara** [TonyHaikara/silk-platform#13]
All the texts have to be written in english.
![silkc1](https://user-images.githubusercontent.com/44141303/120771485-8c186880-c51f-11eb-9540-82e780f3af63.JPG)

**Comment by ywarnier** [comment]
![text-english](https://user-images.githubusercontent.com/609839/132198358-7ac16a7a-eee0-4a60-9985-2255188987b2.png)

C'est maintenant le cas, au moins pour ce message-là.
