### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by PhilippeRaymondHaikara** [TonyHaikara/silk-platform#15]
If there's no result to a research form, show it explicitly (no empty pages)

**Comment by pacman141** [comment]
C'est corrigé  => 

![image](https://user-images.githubusercontent.com/17529387/121319555-a0d47200-c90c-11eb-90b7-d396961fdfb5.png)

**Comment by ywarnier** [comment]
![search-result-empty](https://user-images.githubusercontent.com/609839/132198564-d186b9d9-a87a-4b36-b1df-77d0e2a778d4.png)

Confirmé.
