### ISSUE TITLE
Error creating database structure

### ISSUE THREAD

**Issue by ywarnier** [TonyHaikara/silk-platform#2]
From a fresh installation in the "feature/development" branch: 

```
# php bin/console doctrine:migrations:migrate

 WARNING! You are about to execute a migration in database "silkc" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > yes

[notice] Migrating up to DoctrineMigrations\Version20210517084237
[error] Migration DoctrineMigrations\Version20210413124248 failed during Execution. Error: "An exception occurred while executing 'DROP TABLE récupéré_feuil1':

SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'silkc.récupéré_feuil1'"

In AbstractMySQLDriver.php line 61:
                                                                                             
  An exception occurred while executing 'DROP TABLE récupéré_feuil1':                        
                                                                                             
  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'silkc.récupéré_feuil1'  
                                                                                             

In Exception.php line 18:
                                                                                             
  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'silkc.récupéré_feuil1'  
                                                                                             

In PDOConnection.php line 132:
                                                                                             
  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'silkc.récupéré_feuil1'  
                                                                                             

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
```

Note: tables with accentuated characters are a bad idea ;-)

**Comment by TonyHaikara** [comment]
Les commandes suivantes :
php bin/console doctrine:database:create
php bin/console doctrine:migrations:migrate
fonctionnent bien sur le local.
QUID de la configuration que vous avez en server MySQL ou MariaDB ?

Un fichier de dump de la base de données et ajouté : silk.sql
Il permet de partir d'une version à jour, avec les données Skills et Occupations.

**Comment by ywarnier** [comment]
Le PR que j'ai envoyé sur la branche feature/development règle le problème.
Sur une installation fraîche en local avec une simple connexion à MySQL, il essaie tout de même de reproduire les mêmes CREATE TABLE sur plusieurs tables, de nombreuses fois, mais c'est probablement "simplement" parce que je n'ai pas exécuté silk.sql avant.
Je clôture en tout cas ce rapport, vu qu'il y a une solution, mais je pense qu'on devrait tout de même utiliser les migrations plutôt qu'un .sql séparé (question de bien inscrire le processus d'installation dans un processus évolutif compréhensible par Doctrine et sans problème vis à vis des utilisateurs créés).
