### ISSUE TITLE
Add e-mail validation for new accounts

### ISSUE THREAD

**Issue by ywarnier** [TonyHaikara/silk-platform#5]
La création de comptes devrait être validée par e-mail (on envoie un e-mail avec un lien à l'utilisateur, il clique sur le lien et son compte est validé).

Ça implique d'avoir un champ `validated` et un champ `validation_hash` dans la table user. On peut aussi utiliser un algorithme avec une clef commune pour tout le monde et encrypter l'e-mail avec cet algorithme puis vérifier que le lien cliqué vient bien avec le hash de l'email correspondant (on évite ainsi un champ "validation_hash" qui ne servirait qu'au moment de la création du compte et serait toujours vide ensuite.

**Comment by TonyHaikara** [comment]
Un code de validation est généré à la création d'un compte utilisateur.
Un email est envoyé pour validation.
Tant que le compte n'est pas validé, l'accès à la plateforme est bloqué.

À revoir la configuration des emails pour éviter le spam et configurer l'envoi SMTP.

**Comment by ywarnier** [comment]
L'amélioration visée par ce ticket a été apportée. Je clôture.
