### ISSUE TITLE
Updating pseudo to existing pseudo in DB

### ISSUE THREAD

**Issue by ywarnier** [TonyHaikara/silk-platform#8]
Lorsqu'on essaie de modifier son pseudo pour un pseudo qui existe déjà dans la base de données, on obtient cette erreur:
```
An exception occurred while executing 'UPDATE user SET username = ?, completion = ? WHERE id = ?' with params ["ywarnier", 100, 5]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ywarnier' for key 'UNIQ_8D93D649F85E0677'
```
Il devrait y avoir un check avant la mise à jour pour éviter l'update

**Comment by TonyHaikara** [comment]
Un contrôle est ajouté sur les deux champs unique du compte utilisateur : username et email.
À revoir la redirection et mise en forme erreur affichée.

**Comment by ywarnier** [comment]
![message-username-exists](https://user-images.githubusercontent.com/609839/132196772-c7c3b3d5-0faa-4bc8-838c-2c10d2033587.png)

The current control and message are great! Closing.
