### ISSUE TITLE
My Account goes to personal account, even for institutions

### ISSUE THREAD

**Issue by ywarnier** [TonyHaikara/silk-platform#9]
When connecting as an *institutional* user, clicking in the user menu on "My Account" sends me to https://silkc-platform.org/account, which offers me the "personal informations" tab, which is only for *individual* users.

![silkc-platform-202105-5](https://user-images.githubusercontent.com/609839/119334449-6e2f4600-bc8b-11eb-9bcd-f06edf3cfa60.png)

**Comment by pacman141** [comment]
Le lien dirige maintenant vers "My institution"

**Comment by ywarnier** [comment]
This issue has been successfully fixed (possibly by 4e6af6e81efec7e2348317cf4df4d0ad982d1b65 ?)
